### ISSUE TITLE
誤植？2章

### ISSUE THREAD

**Issue by takakubo** [ghmagazine/rstudiobook_v2#10]
下記、css内の `html > ` は不要ではないでしょうか？

https://github.com/ghmagazine/rstudiobook_v2/blob/8caf387f7179fcf1743cbcdf9f56e10369f51ca4/sample_code/chapter2_scraping.R#L31-L33

**Comment by yutannihilation** [comment]
ご報告ありがとうございます、たしかに不要そうです。

@ymattu 
正誤表への追加をお願いしてもいいでしょうか。第一版でこの直前の行について正誤表が出ていますが、そのときの修正漏れなのではないかと思います。

https://gihyo.jp/book/2018/978-4-7741-9853-8/support/

**Comment by yutannihilation** [comment]
正誤表に反映しました。ご報告ありがとうございました！
